# Generated by Django 2.2.24 on 2021-07-23 16:40

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='project',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='projectitem',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='projectitem',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
