# Generated by Django 2.2.24 on 2021-07-25 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20210724_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('c', 'Completed'), ('o', 'On Progress')], default='o', max_length=1, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='projectitem',
            name='status',
            field=models.CharField(choices=[('c', 'Completed'), ('o', 'On Progress')], default='o', max_length=1, verbose_name='status'),
        ),
    ]
